.login: &login
    - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin

.deploy: &deploy
    - *login
    - docker rm -f ffc_backend_api || true
    - docker rm -f ffc_backend_redis || true
    - docker-compose pull
    - docker-compose up -d

stages:
    - build
    - deploy

build:
    stage: build
    tags:
        - ffcbuilder
    script:
        - *login
        - docker-compose build
        - docker-compose push

staging_deploy:
    stage: deploy
    when: manual
    tags:
        - ffcstaging
    script:
        - *deploy

production_deploy:
    stage: deploy
    when: manual
    tags:
        - ffcproduction
    script:
        - *deploy
