.set_docker_image_tag: &set_docker_image_tag
    - eval "[ -z "$CI_COMMIT_TAG" ] && export DOCKER_IMAGE_TAG=$CI_COMMIT_SHORT_SHA || export DOCKER_IMAGE_TAG=$CI_COMMIT_TAG"

.deploy: &deploy
    - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
    - docker rm -f ffc_backend_api || true
    - docker rm -f ffc_backend_redis || true
    - docker-compose pull
    - docker-compose up -d

stages:
    - build
    - deploy

build:build:
    stage: build
    tags:
        - builder
    before_script:
        - *set_docker_image_tag
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - docker-compose build
        - docker-compose push

deploy:testing:
    stage: deploy
    when: manual
    tags:
        - ffcstaging
    before_script:
        - *set_docker_image_tag
    script:
        - *deploy
    dependencies:
        - build:build

deploy:staging:
    stage: deploy
    when: manual
    tags:
        - ffcstaging
    before_script:
        - *set_docker_image_tag
    script:
        - *deploy
    dependencies:
        - build:build

deploy:production:
    stage: deploy
    when: manual
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
    tags:
        - ffcproduction
    before_script:
        - *set_docker_image_tag
    script:
        - *deploy
    dependencies:
        - build:build
