.deploy: &deploy
    - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
    - docker rm -f ffc_backend_api || true
    - docker rm -f ffc_backend_redis || true
    - docker-compose pull
    - docker-compose up -d

stages:
    - build
    - deploy

build:build:
    stage: build
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
    tags:
        - ffcbuilder
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - docker-compose build
        - docker-compose push

deploy:staging:
    stage: deploy
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
    when: manual
    tags:
        - ffcstaging
    script:
        - *deploy
    dependencies:
        - build:build

deploy:production:
    stage: deploy
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
    when: manual
    tags:
        - ffcproduction
    script:
        - *deploy
    dependencies:
        - build:build