#caching modules
cache:
    paths:
      - node_modules/
      - .yarn
stages:
    - deploy

testing_deploy:
    stage: deploy
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)-test\d*$/
    tags:
        - testserver
    script:
        - echo "Building and deploying ffc_janus staging."
        - docker rm -f ffc_backend_web ffc_backend_redis ffc_backend || true
        - docker-compose build
        - docker network rm freeflowconnect-backend_ffc_backend
        - docker network create --driver bridge --ipv6 --subnet 2a02:1811:b229:9f03:0:0:0:0/64 freeflowconnect-backend_ffc_backend --attachable
        - docker-compose up -d

staging_deploy:
    stage: deploy
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)-rc\d*$/
    tags:
        - testserver
    script:
        - echo "Building and deploying ffc_janus staging."
        - docker rm -f ffc_backend_web ffc_backend_redis ffc_backend || true
        - docker-compose build
        - docker network rm freeflowconnect-backend_ffc_backend
        - docker network create --driver bridge --ipv6 --subnet 2a02:1811:b229:9f03:0:0:0:0/64 freeflowconnect-backend_ffc_backend --attachable
        - docker-compose up -d
    
deploy:
    stage: deploy
    only:
        - /^(\d+\.)?(\d+\.)?(\*|\d+)$/
    tags:
        - testserver
    script:
        - echo "Building and deploying ffc_janus production."
        - docker rm -f ffc_janus || true
        - docker build -t 3bot_app_jimber/freeflowconnect-backend:$CI_COMMIT_TAG .
        - docker run -d -it --name=ffc_backend --network=ffc_backend 3bot_app_jimber/freeflowconnect-backend:$CI_COMMIT_TAG
    