.deploy: &deploy
    - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
    - docker rm -f ffc_backend_api || true
    - docker rm -f ffc_backend_redis || true
    - docker-compose pull
    - docker-compose up -d

stages:
    - build
    - deploy

build:build:
    stage: build
    variables:
        DOCKER_IMAGE_TAG: '${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}'
    tags:
        - ffcbuilder
    script:
        - echo "$DOCKER_PW" | docker login -u $DOCKER_USER --password-stdin
        - echo ${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}
        - echo $DOCKER_IMAGE_TAG
        - echo ${DOCKER_IMAGE_TAG}
        - docker-compose build
        - docker-compose push

deploy:testing:
    stage: deploy
    when: manual
    variables:
        DOCKER_IMAGE_TAG: '${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}'
    tags:
        - ffcstaging
    script:
        - *deploy
    dependencies:
        - build:build

deploy:staging:
    stage: deploy
    when: manual
    variables:
        DOCKER_IMAGE_TAG: '${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}'
    tags:
        - ffcstaging
    script:
        - *deploy
    dependencies:
        - build:build

deploy:production:
    stage: deploy
    when: manual
    only:
        - /^v(\d+\.)?(\d+\.)?(\*|\d+)$/
    variables:
        DOCKER_IMAGE_TAG: '${CI_COMMIT_TAG:-$CI_COMMIT_SHORT_SHA}'
    tags:
        - ffcproduction
    script:
        - *deploy
    dependencies:
        - build:build
