version: '3.3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "3bot_app_jimber/freeflowconnect-backend:staging"
    container_name: ffc_backend
    restart: always
    networks:
      - ffc_backend

networks:
  ffc_backend: