version: '3.3'
services:

  web:
    build: .
    container_name: ffc_backend_web
    restart: always
    ports:
      - "5000:5000"
    networks:
      ffc_backend:
        ipv6_address: 2a02:1811:b229:9f03:0:0:0:2
  redis:
    image: "redis:alpine"
    container_name: ffc_backend_redis
    restart: always
    networks:
      ffc_backend:
        ipv6_address: 2a02:1811:b229:9f03:0:0:0:3

networks:
  ffc_backend:
    driver: bridge
    driver_opts:
      enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.23.0.0/16
      - subnet: 2a02:1811:b229:9f03:0:0:0:0/64