version: '3.7'
services:

  web:
    build: .
    container_name: ffc_backend_web
    restart: always
    volumes:
      - /opt/freeflow/config/freeflow_config.py:/usr/share/nginx/config/freeflow_config.py
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
    container_name: ffc_backend_redis
    restart: always