version: '3.3'
services:

  web:
    build: .
    container_name: ffc_backend_web
    restart: always
    ports:
      - "5000:5000"
    networks:
      - ffc_backend
  redis:
    image: "redis:alpine"
    container_name: ffc_backend
    restart: always
    networks:
      - ffc_backend

networks:
  ffc_backend: