version: "3.3"
services:
  ffc_backend_api:
    build: .
    image: "jimber/ffc_backend_api-${ENVIRONMENT}:${CI_COMMIT_TAG}"
    container_name: "ffc_backend_api"
    volumes:
      - /opt/freeflow/config/freeflow_config.py:/usr/share/nginx/config/freeflow_config.py
    ports:
      - "5000:5000"
    networks:
      - ffc_network
    restart: always
  ffc_backend_redis:
    image: "redis:alpine"
    container_name: "ffc_backend_redis"
    networks:
      - ffc_network
    restart: always
networks:
  ffc_network:
    external: true