version: '3.3'
services:

  web:
    build: 
      context: ./
    container_name: ffc_backend_web
    restart: always
    volumes:
      - /opt/freeflow/config/freeflow_config.py:/usr/share/nginx/config/freeflow_config.py
    ports:
      - "5000:5000"
    networks:
      ffc_backend:
        ipv6_address: 2a02:1811:b229:9f03:0:0:0:2
  redis:
    image: "redis:alpine"
    container_name: ffc_backend_redis
    restart: always
    networks:
      ffc_backend:
        ipv6_address: 2a02:1811:b229:9f03:0:0:0:3

networks:
  ffc_backend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 2a02:1811:b229:9f03:0:0:0:0/64